# -*- coding: utf-8 -*-

import importlib
import importlib.util
import os
import setuptools

"""This file is used to package the reporteditor plugin.

- It was generated by the InvenTree Plugin Creator tool - version 1.2.0
- Ref: https://github.com/inventree/plugin_creator
"""

"""Read the plugin version from the source code."""
module_path = os.path.join(os.path.dirname(__file__), "report_editor", "__init__.py")
spec = importlib.util.spec_from_file_location("report_editor", module_path)
report_editor = importlib.util.module_from_spec(spec)
spec.loader.exec_module(report_editor)

with open('README.md', encoding='utf-8') as f:
    long_description = f.read()

setuptools.setup(
    name="report_editor",
    version=report_editor.PLUGIN_VERSION,
    author="wolflu05",
    author_email="76838159+wolflu05@users.noreply.github.com",
    description="A report editor plugin that is powered by an LSP",
    long_description=long_description,
    long_description_content_type='text/markdown',
    url="https://github.com/wolflu05/inventree-report-editor-plugin",
    license="MIT",
    packages=setuptools.find_packages(),
    include_package_data=True,
    install_requires=[
        # Enter your plugin library dependencies here
    ],
    setup_requires=[
        "wheel",
        "twine",
    ],
    python_requires=">=3.9",
    entry_points={
        "inventree_plugins": [
            "reporteditor = report_editor.core:reporteditor"
        ]
    },
)
